### PR TITLE
Add P10 divide/modulo operations for quadword.

### PR DESCRIPTION
**Pull request by munroesj52**
POWER10 added vector divde/divide-extended/modulo instructions. This is the initial patch for the quadword implementations. Also some general Wall fixups and latent compile error fixes. A later patch will add the platform specific implementations for static and IFUNC enabled dynamic libraries.

	* doc/pveclib-doxygen-pveclib.doxy [FORMULA_TRANSPARENT, LATEX_SOURCE_CODE, CLASS_DIAGRAMS, DOT_FONTNAME, DOT_FONTSIZE, DOT_TRANSPARENT]: Remove tags that are no longer support is recent doxygen versions.
	* doc/pveclibmaindox.h: Escape \# for pragma to fix formating.

	* src/pveclib/vec_int128_ppc.h: Update copyright year. General doxygen text updates, mostly POWER10 related. [int128_multiply_0_1]: New Subsection Implementing Quadword Multiply. [int128_multiply_0_1_0_0]: New subsubsection POWER7/8 Implementation of Quadword Multiply. [int128_multiply_0_1_0_1]: New subsubsection POWER9/10 Implementation of Quadword Multiply. [int128_multiply_0_1_1]: New subsubsection Implementing Quadword Multiply High. [int128_multiply_0_1_2]: New subsubsection Implementing Quadword Multiply Low. [int128_multiply_0_1_3]: New subsubsection Implementing Quadword Multiply with double Quadword result. [int128_Divide_0_1]: New subsection Implementing Quadword Divide/Modulo. [int128_Divide_0_1_1]: New subsubsection Vectorizable Divide implementations. [int128_Divide_0_1_1_1]: New paragraph Vectorized Shift-Subtract Quadword Divide. [int128_Divide_0_1_1_2]: New paragraph Vectorized Quadword Long division. [int128_Divide_0_1_1_3]: New paragraph Divide Quadword implementation. [int128_Divide_0_1_1_4]: New paragraph Divide Extended Quadword implementation. [int128_Divide_0_1_1_5]: New paragraph Quadword Modulo implementation. [int128_Divide_0_1_1_6]: New paragraph Double Quadword Divide implementation. (__VEC_U_128P): New type quadword integer pair. (vec_vdivuqe_inline, vec_vdivuq_inline, vec_vmoduq_inline, vec_divdqu_inline, vec_seluq, vec_vmsumcud_inline, vec_vmsumudm_inline): New Forward function prototypes. (vec_divduq, vec_divuqe, vec_divuq): New functions. (vec_divdqu_inline, vec_modduq, vec_moduq): New functions. (vec_msumudm): Update brief description. (vec_mulhuq): Update brief description. (vec_mulhuq [_ARCH_PWR10]): Add POWER10 specific implementation. (vec_mulluq): Update brief description. (vec_mulhuq [_ARCH_PWR9]): Update POWER9 specific implementation. (vec_muludq): Update brief description. (vec_muludq [_ARCH_PWR10]): Add POWER10 specific implementation. (vec_muludq [_ARCH_PWR9]): Update POWER9 specific implementation. (vec_slqi [_ARCH_PWR10]): Fix for POWER10 specific implementation. (vec_vdivuqe_inline, vec_vdivuq_inline, vec_vmoduq_inline): New functions. (vec_vmuleud): Update brief description. (vec_vmulhud_inline): New functions. (vec_vmulld_inline): Add POWER10 specific implementation. (vec_vmuloud): Update brief description. (vec_vmsumcud_inline, vec_vmsumudm_inline): New functions.

	* src/pveclib/vec_int64_ppc.h[i64_missing_ops_0_2_2_1]: Add ref to doxygen description. (vec_divqud_inline [_ARCH_PWR9]):Fix for POWER9 specific compiler issue. (vec_moddud_inline): Fix Wall warning.

	* src/testsuite/arith128_test_i128.c (db_vec_divuqe, db_vec_divuq, db_vec_divdqu, db_vec_moduq): New dubug functions. (test_vec_divide_QW, test_vec_modulo_QW, test_vec_moddiv_QW, test_vec_divext_QW, est_vec_div1_QW, test_vec_div_QW): New unit test functions. (test_vec_i128): Call new unit tests from driver.

	* src/testsuite/arith128_test_i512.c (test_mul512x128): Additional cases for unit test.

	* src/testsuite/vec_f128_dummy.c (test_vec_msubqpo); Fix Wall warning.
	* src/testsuite/vec_int128_dummy.c (test_divuqe, test_divuq, test_moduq, test_divduq, test_modduq, test_divdqu): Inline expantion compile test. (test_vec_mulqud, test_vec_xxx; test_vec_xxx_V2, test_vec_xxx_V1, test_vec_xxx_V0): compile tests. (test_vec_divuqe, test_vec_divuq, test_vec_divduq, test_vec_divdqu): Implementation compile tests. (test_vec_udivqi3): compile tests. (test_vec_moduq, test_vec_modduq): Implementation compile tests. (__test_cmsumudm_V2): compile tests.
	* src/testsuite/vec_int64_dummy.c (test_vec_divude, test_vec_divdud_V1[_ARCH_PWR8]): Fix Wall warnings.
	* src/testsuite/vec_pwr10_dummy.c (test_divuqe_PWR10, vec_vdivuqe_inline, test_divuq_PWR10, test_moduq_PWR10, test_divduq_PWR10, test_modduq_PWR10, test_vec_mulqud_PWR10): Implementation compile tests. (__test_splatudi_12_PWR10 [_ARCH_PWR10 && (__GNUC__ > 11)]): Guard using intrinsic vec_splati for compiler support. (test_gcc_cmpsq_all_gt_PWR10, test_gcc_cmpsq_gt_PWR10 [_ARCH_PWR10 && (__GNUC__ > 11)]): Guard using intrinsic ec_cmpgt for signed __int128 for compiler support. (__test_cmsumudm_V2_PWR10, test_vec_slqi_8_PWR10): Implementation compile tests. (__test_mulluq_V1_PWR10, __test_muludq_V1_PWR10, test_vec_moddivduq_PWR10): Compile test for code generation.
	* src/testsuite/vec_pwr9_dummy.c (test_vec_msubqpo_PWR9): Fix Wall warning. (__test_cmsumudm_V2_PWR10, __test_mulhuq_x_PWR9, __test_mulluq_V1_PWR9, __test_muludq_w_PWR9): Compile test for code generation. (test_divuqe_PWR9, test_divuq_PWR9, test_moduq_PWR9, test_divduq_PWR9, test_modduq_PWR9, test_divdqu_PWR9): Implementation compile tests. (test_vec_moddivduq_PWR9): Compile test for code generation.

	* src/testsuite/pveclib_perf.c ()test_time_i128): Add timed tests for quadword divide.
	* src/testsuite/vec_perf_i128.c (c152): Constant 10**152-1. (timed_vec_divdqu, timed_vec_divuqe, timed_vec_divuq, timed_vec_divuq2): Timed test for new PVEVLIB functions. (timed_gcc_divuq, timed_gcc_divuq2): Timed libgcc functions for comparison. (test_divdqu): Timed test for new PVEVLIB functions. (timed_divmodud): Fix Wall warnings.
	* src/testsuite/vec_perf_i128.h (timed_vec_divdqu, timed_vec_divuqe, timed_vec_divuq, timed_vec_divuq2, timed_gcc_divuq, timed_gcc_divuq2): New externs for timed tests.

### CODE REVIEW

**Comment by munroesj52** [comment]
Tulio just a heads up on what i amd doing. If you are buzy I'll push this in about a week.

**Comment by tuliom** [comment]
This is a very long patch. I'd need a lot more time to review everything.
I did a fast look and I couldn't spot any issues.
The tests are passing too.

**Review by tuliom — APPROVED** [review]

**Comment by munroesj52** [comment]
Ya I sorta get caught in this loop of starting a specific change (P10 divide) then finding 3-4 other needed changes, then starting to update documentation and in the process seeing 4-5 other missed opportunities, ... 

It neaver seems to end.  More reviewers would help.

**Comment by munroesj52** [comment]
Thanks Tulio. moving on to itn64 divide library support.

**Pull request merged**
