### PR TITLE
Fix problems for GCC V12 turning off -many

### PR DESCRIPTION
**Pull request by munroesj52**
PVECLIB compile fails for GCC12 as reported:
https://github.com/advancetoolchain/advance-toolchain/pull/2275

Seems GCC V12 wants to disable explicitly enabling -many for
assembly. vec_f128_dummy.c had some perf code trying to compare
hard/soft-float performance using in-line __builtin_cpu_supports.
This trick requires -many to work. So disable them for now, but
will need something similar for perf testing the round-to-odd
implementations.

	* src/testsuite/pveclib_perf.c: Add commment about disabling
	some tests until the F128 round-to-odd implementations are
	ready.

	* src/testsuite/vec_f128_dummy.c (test_scalar_add128,
	test_scalar_div128, test_scalar_mul128, test_scalar_sub128):
	Remove __builtin_cpu_supports code. Conditionally Disable the
	lot.

	* src/testsuite/vec_perf_f128.c (test_scalar_add128,
	test_scalar_div128, test_scalar_mul128, test_scalar_sub128):
	Conditionally Disable these externs.
	(test_scalarLib_expxsuba_128):
	Conditionally Disable this perf-test.
	(timed_expxsuba_v2_f128):
	Conditionally Disable this perf-test.

	* src/testsuite/vec_perf_f128.h (timed_expxsuba_v1_f128.
	timed_expxsuba_v2_f128): Conditionally Disable these externs.

Signed-off-by: Steven Munroe <munroesj52@gmail.com>

### CODE REVIEW

**Review by ThinkOpenly — CHANGES_REQUESTED** [review]
Could you just do something like:
```
.machine push
.machine "power9"
[power9 instruction]
.machine pop
```
or as a one-liner:
```
__asm__ __volatile__ (                                              \
      ".machine push; .machine \"power9\"; mffsl %0; .machine pop"      \
      : "=f" (__fr));
```

**Comment by munroesj52** [comment]
I will include these in examples later. But I think this specific code will be replaced by IFUNC implementations.
This will be part of the F128 runtime library and not in a compile dummy.

So can I merge this?

**Review by ThinkOpenly — APPROVED** [review]
as you wish.

**Comment by munroesj52** [comment]
Did you test this against AT16?

**Comment by munroesj52** [comment]
Fixes https://github.com/open-power-sdk/pveclib/issues/150 I think.

**Pull request merged**
