### PR TITLE
Move headers to pveclib subdir

### PR DESCRIPTION
**Pull request by gftg85**
In the process of packaging this project for Debian [1], I noticed that it could be better for users if they didn't have to use `-I/path/to/pveclib` (see commit message).  This pull request implements this idea and I would like to listen to feedback before I move forward with the packaging.

[1] https://bugs.debian.org/929405

### CODE REVIEW

**Comment by munroesj52** [comment]
But at minimum it would require the using application to reconfigure to pick up the new path. So it is not build compatible and could cause built failures. A minor version change seems prudent.

**Comment by gftg85** [comment]
> It's a binary-compatible change, right? If a user was specifying `-I/<path>/pveclib` and using `#include <vec_int128_ppc.h>`, that will still work after the change unless I'm missing something.

It will work exactly like this.  Any header included by the user without `pveclib/`, for instance `#include <vec_int128_ppc.h>` will be found by the additional `-I/<path>/pveclib`, whereas the include directives in pveclib headers, which after this patch contain `pveclib/`, will be found by the search path hardcoded in the compiler, i.e.: `/usr/include`.

>Oh, maybe the `-I/<path>/pveclib` has to change to `-I/<path>/pveclib/pveclib` ?

No, this is not needed.  I tested on the powerpc64le machine (minicloud) I am using to develop the package.

>Since `/<path>/pveclib` is not very explicit or precise, it's a little tough to say definitively.

Currently, the package installs the header files under `/usr/include/pveclib`.  This is the output of `dpkg -L libpvec-dev`:

```
/.
/usr
/usr/include
/usr/include/pveclib
/usr/include/pveclib/vec_bcd_ppc.h
/usr/include/pveclib/vec_char_ppc.h
/usr/include/pveclib/vec_common_ppc.h
/usr/include/pveclib/vec_f128_ppc.h
/usr/include/pveclib/vec_f32_ppc.h
/usr/include/pveclib/vec_f64_ppc.h
/usr/include/pveclib/vec_int128_ppc.h
/usr/include/pveclib/vec_int16_ppc.h
/usr/include/pveclib/vec_int32_ppc.h
/usr/include/pveclib/vec_int64_ppc.h
/usr/lib
/usr/lib/powerpc64le-linux-gnu
/usr/lib/powerpc64le-linux-gnu/libpvec.a
/usr/lib/powerpc64le-linux-gnu/libpvec.la
/usr/share
/usr/share/doc
/usr/share/doc/libpvec-dev
/usr/share/doc/libpvec-dev/changelog.Debian.gz
/usr/share/doc/libpvec-dev/copyright
/usr/lib/powerpc64le-linux-gnu/libpvec.so
```

**Comment by gftg85** [comment]
> But at minimum it would require the using application to reconfigure to pick up the new path. So it is not build compatible and could cause built failures. A minor version change seems prudent.

Actually, there's no change in [installation] paths.  The header are all under `/usr/include/pveclib`, for instance `/usr/include/pveclib/vec_bcd_ppc.h`, **with or without** this patch.  What has changed is the way that installed headers include each other.

**Comment by gftg85** [comment]
By the way, my previous comments don't mean that I am against the version bump.  As a matter of fact, it would be better from a Debian perspective, because with the version bump, I wouldn't need to carry this patch downstream (I could simply sync the sources).

**Comment by gftg85** [comment]
> Actually, there's no change in [installation] paths. The headers are all under `/usr/include/pveclib`, for instance `/usr/include/pveclib/vec_bcd_ppc.h`, **with or without** this patch. What has changed is the way that installed headers include each other.

I just noticed that this implies that the short description of the patch (first line of the commit message) is very misleading. I'll rewrite it.

**Comment by gftg85** [comment]
I just pushed a new version of this patch, in which I only changed the commit message.  I hope that helps.

A question...  You mentioned a bump in the package version is needed, but I expected this to be done in a separate commit (one similar to 31bc2be095).  Let me know if I got it wrong.

**Comment by munroesj52** [comment]
Change the AC_INIT version to [1.0.1] and push to master. Then some more
testing across compilers (AT10/11/12) and platforms (POWER7/8/9).

After successful tests we can tag 1.0.1 and use that for submission to
Fedora and Debian.

Almost forgot.

Looks like the fedora RPM spec wants a ChangeLog.md which pveclib does not
have.
Niether does libsphde but does have:
https://github.com/sphde/sphde/blob/master/generate-changelog.sh

Does pveclib need a generate-changelog.sh?

**Comment by gftg85** [comment]
> Almost forgot.
>
> Looks like the fedora RPM spec wants a ChangeLog.md which pveclib does not have.
> Niether does libsphde but does have: https://github.com/sphde/sphde/blob/master/generate-changelog.sh
>
> Does pveclib need a generate-changelog.sh?

I can't speak for Fedora, because I'm not used to their packaging guidelines, but Debian does not require it (per [Debian Policy 12.7](https://www.debian.org/doc/debian-policy/ch-docs.html#changelog-files-and-release-notes)).

**Comment by gftg85** [comment]
>Change the AC_INIT version to [1.0.1] and push to master. Then some more testing across compilers (AT10/11/12) and platforms (POWER7/8/9).

I don't have commit access to this repository, but I could add a commit to this pull request with the change to `AC_INIT` (or even include the change in the current commit... it works the same for me).  Is that your suggestion?

**Comment by munroesj52** [comment]
so ... I'll do the AC_INIT version change add generate-changelog.sh (to make fedora happy) and tag v1.0.1 as a separate update.

There is one more clean up needed; arith128.h is not used (any more) by tipowof10.c, so the #include line should be removed. But it is still use by various sources from ./testsuite. So this header file should be moved there. 

All this is getting messy with separate pulls and multiple commits. Please generate a new pull consolidating all proposed changes for final review and commit. Please include then suggested change to tipowof10.c and move arith128.h into ./testsuite/

thanks

**Comment by gftg85** [comment]
Superseded by pull request #73.

**Pull request closed without merging**
