### PR TITLE
Updates to resolve PRs 1987863 and 1992484

### PR DESCRIPTION
**Pull request by munroesj52**
Update configure.ac for autotools 2.71 and fix compile errors from
GCC 11.

	* configure.ac: Replace AC_PROG_LIBTOOL with LT_INIT.

	* Makefile.in: Regenerate.
	* aclocal.m4: Regenerate.
	* configure: Regenerate.
	* src/Makefile.in: regenerate.

	* src/pveclib/vec_int128_ppc.h (vec_sraq): Cast from
	vec_setb_sq() to (vui128_t).
	(vec_sraqi): Cast from vec_setb_sq() to (vui128_t).
	* src/testsuite/vec_int128_dummy.c (test_setb_cyq,
	test_setb_ncq, test_setb_sq): Change type of function result to
	vb128_t.
	* src/testsuite/vec_perf_f64.c (timed_fpclassify_f64):
	Change type of accum to vui64_t.

Signed-off-by: Steven Munroe <munroesj52@gmail.com>

### CODE REVIEW

**Comment by munroesj52** [comment]
Still confused by the conflicting files. As far I can tell git is unhappy that autotools version are newer than master?

**Comment by mscastanho** [comment]
@munroesj52 I think the issue is that your PR is based on top of the `stable/1.0.4-4` branch, but you're trying to merge against the `master` branch, which is many commits ahead. If you plan to modify the stable branch, you may need to [change the target branch of your PR](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#changing-the-branch-range-and-destination-repository).

**Comment by munroesj52** [comment]
Actually this branch is based on tag v1.0.4
and I am trying to merge to stable/1.0.4-4

What am I doing wrong this time.

**Comment by tuliom** [comment]
@munroesj52 It looks like this pull request has already been pushed to stable/1.0.4-4.

**Review by tuliom — APPROVED** [review]

**Comment by munroesj52** [comment]
So I don't need to merge to master.

Seems like i really don't want to do that

So can I just "tag" stable/1.0.4-4?
git checkout stable/1.0.4-4
git tag v1.0.4-4
git push origin stable/1.0.4-4

seems to work locally
$git show v1.0.4-4
commit 60759126a0f6746987a0897315ea4d34a2d430aa (HEAD -> stable/1.0.4-4,
tag: v1.0.4-4, origin/stable/1.0.4-4)
Author: Steven Munroe ***@***.***>
Date:   Mon Aug 16 15:57:21 2021 -0500

    Updates to resolve PRs 1987863 and 1992484
...

but does show as a new tag on github?

I need something for the fedora spec file.

**Comment by tuliom** [comment]
> but does show as a new tag on github?

@munroesj52 No, after you created the tag locally, you have to push the tag to github, e.g.: `git push origin v1.0.4-4`

**Comment by munroesj52** [comment]
Ok so not I have the tag v1.0.4-4, but:

> $ cd ../tmp/
>> ***@***.***:~/work/tmp$ git clone -b v1.0.4-4
>> https://github.com/open-power-sdk/pveclib.git
>> Cloning into 'pveclib'...
>> remote: Enumerating objects: 2232, done.
>> remote: Counting objects: 100% (381/381), done.
>> remote: Compressing objects: 100% (251/251), done.
>> remote: Total 2232 (delta 279), reused 187 (delta 130), pack-reused 1851
>> Receiving objects: 100% (2232/2232), 2.35 MiB | 6.29 MiB/s, done.
>> Resolving deltas: 100% (1657/1657), done.
>> Note: switching to '60759126a0f6746987a0897315ea4d34a2d430aa'.
>>
>> You are in 'detached HEAD' state. You can look around, make experimental
>> changes and commit them, and you can discard any commits you make in this
>> state without impacting any branches by switching back to a branch.
>>
>> If you want to create a new branch to retain commits you create, you may
>> do so (now or later) by using -c with the switch command. Example:
>>
>>   git switch -c <new-branch-name>
>>
>> Or undo this operation with:
>>
>>   git switch -
>>
>> Turn off this advice by setting config variable advice.detachedHead to
>> false
>>
>
Can I assume this is just a friendly warning that should not be a problem
for Fedora fedpkg?

**Comment by tuliom** [comment]
> Can I assume this is just a friendly warning that should not be a problem for Fedora fedpkg?

@munroesj52 yes.
`spectool -g pveclib.spec` should still be able to download the source code.

**Comment by munroesj52** [comment]
I assume this pull request is not needed and should be closed

**Comment by tuliom** [comment]
> I assume this pull request is not needed and should be closed

@munroesj52 As the patches have already been merged, I agree it can be closed.
More importantly, it has already been reviewed too, so it can be closed without requiring new changes.

**Comment by munroesj52** [comment]
looks like this all fell through the cracks:

https://bugzilla.redhat.com/show_bug.cgi?id=1943053
https://bugzilla.redhat.com/show_bug.cgi?id=1999514

My update should have fixed this but I am not sure what they think failed?

**Comment by tuliom** [comment]
@munroesj52 The [Fedora pull request](https://src.fedoraproject.org/rpms/pveclib/pull-request/1) is pending review/merge.

**Pull request closed without merging**
